name: Artemis plugin

on: [push]

jobs:
  build:
    runs-on: [windows-latest]

    steps:
      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Clone RGB.NET
        uses: actions/checkout@v2
        with:
          repository: DarthAffe/RGB.NET
          path: RGB.NET
          ref: Development

      - name: Build RGB.NET
        run: dotnet build .\RGB.NET\RGB.NET.Core\RGB.NET.Core.csproj
      - run: dotnet build .\RGB.NET\RGB.NET.Layout\RGB.NET.Layout.csproj
      - run: dotnet build .\RGB.NET\RGB.NET.Presets\RGB.NET.Presets.csproj

      - name: Clone Artemis
        uses: actions/checkout@v2
        with:
          repository: Artemis-RGB/Artemis
          path: Artemis
          ref: development

      - name: Build Artemis
        run: dotnet build .\Artemis\src\Artemis.sln

      - name: Clone Plugins
        uses: actions/checkout@v2
        with:
          path: Plugins

      - name: Build Plugins
        run: dotnet publish -c Release .\Plugins\src\Artemis.Plugins.Modules.RocketLeague\Artemis.Plugins.Modules.RocketLeague.csproj

      - name: Upload Artemis plugin
        uses: actions/upload-artifact@v2
        with:
          name: Artemis.Plugins.Modules.RocketLeague
          path: .\Plugins\src\Artemis.Plugins.Modules.RocketLeague\bin\Release\net5.0-windows\publish