name: BakkesMod plugin

on: [push]

jobs:

  build:
    runs-on: [windows-latest]

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout BakkesMod SDK
      uses: actions/checkout@v2
      with:
        repository: bakkesmodorg/BakkesModSDK
        path: bakkesmodsdk

    - name: Fix path
      shell: powershell
      run: (Get-Content '.\src\ArtemisGSI\BakkesMod.props').Replace('$(registry:HKEY_CURRENT_USER\Software\BakkesMod\AppPath@BakkesModPath)','$(ProjectDir)\..\..\') | Set-Content '.\src\ArtemisGSI\BakkesMod.props'

    - name: Build BakkesMod Plugin
      run: MSBuild.exe .\src\ArtemisGSI\ArtemisGSI.vcxproj /p:Platform=x64 /p:Configuration=Release

    - name: Upload BakkesMod Plugin
      uses: actions/upload-artifact@v2
      with:
        name: ArtemisGSI
        path: .\src\ArtemisGSI\plugins\ArtemisGSI.dll