name: BakkesMod plugin

on: push

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        path: plugin

    - name: Checkout BakkesMod SDK
      uses: actions/checkout@v3
      with:
        repository: bakkesmodorg/BakkesModSDK
        path: plugin\bakkesmodsdk

    - name: Build
      run: msbuild /m /p:Configuration=Release /p:BakkesModPath=$env:GITHUB_WORKSPACE\plugin /p:Environment=GitHub $env:GITHUB_WORKSPACE\plugin\src\Artemis.GSI.RocketLeague.sln

    - name: Upload BakkesMod Plugin
      uses: actions/upload-artifact@v3
      with:
        name: ArtemisGSI
        path: .\plugin\src\plugins\ArtemisGSI.dll